env = Environment(CPPPATH='#',
                CPPDEFINES=[],
                LIBS=[],
                CXXFLAGS='-std=c++0x'
                )
src = ["q_1_2.cpp", "q_1_6.cpp"]
for file in src: 
    env.Program(file)
